#pragma once
#include "blackshift_core.h"
#include <vector>

// Vertices of a rigid model generated by the Rust core; empty if the model is unknown.
inline std::vector<BsVertex> modelVertices(BsModel model) {
    std::vector<BsVertex> vertices(size_t(bs_mesh_vertex_count(model)));
    if (bs_mesh_vertices(model, vertices.data(), int(vertices.size())) != int(vertices.size()))
        vertices.clear();
    return vertices;
}
